---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileshare
spec:
#  storageClassName: csi-ceph-hdd-ms1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi