---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: quay.io/testing-farm/nginx:1.13
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi