---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: quay.io/testing-farm/nginx:1.12
          name: nginx
          envFrom:
            - configMapRef:
                name: nginx-configmap-env
          env:
            - name: TEST
              value: foo
            - name: TEST_1
              valueFrom:
                secretKeyRef:
                  name: nginx-secret
                  key: dbpass
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
...