---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 60 # TTL is a new feature in Kubernetes 1.12 that allows you to set a time to live for a resource.
  template:
    spec:
      containers:
        - name: hello
          image: quay.io/prometheus/busybox
          args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
      restartPolicy: Never